import { transformerTwoslash } from "@shikijs/vitepress-twoslash";
import { defineConfig } from "vitepress";
import typedocSidebar from "../reference/typedoc-sidebar.json" with { type: "json" };
import { SDK_VERSION } from "./config/build-info.ts";
import { footerMessage } from "./config/footer.ts";
import { guideSidebar } from "./config/sidebar.ts";
import { twoslashCompilerOptions } from "./config/twoslash.ts";

export default defineConfig({
    title: "Lelantos SDK",
    description:
        "Client SDK for the Lelantos Multi-Asset Shielded Pool — shielded transfers, swaps, and client-side proving on EVM.",
    lang: "en-US",
    cleanUrls: true,
    // A dead link is a docs bug; fail the build rather than ship one. The one
    // exemption is viem's own JSDoc, which reaches the reference through
    // ViemChainAdapter's inherited method docs and contains site-relative links
    // (/docs/glossary/terms#filter) that only resolve on viem.sh. Scoped to that
    // prefix so every other link stays checked.
    ignoreDeadLinks: [/^\/docs\/glossary\//],
    head: [
        ["link", { rel: "icon", href: "/icon.svg", type: "image/svg+xml" }],
        ["meta", { name: "theme-color", content: "#4f46e5" }],
        ["meta", { property: "og:type", content: "website" }],
        ["meta", { property: "og:title", content: "Lelantos SDK" }],
        ["meta", { property: "og:url", content: "https://docs.lelantos.xyz" }],
    ],
    markdown: {
        codeTransformers: [
            transformerTwoslash({
                // Never silently downgrade to plain highlighting: a snippet
                // that stops compiling must break the build, not the docs.
                throws: true,
                twoslashOptions: { compilerOptions: twoslashCompilerOptions },
            }),
        ],
        // Twoslash renders types into the DOM; Vue would try to parse the
        // braces in generic signatures like `Result<{ a: string }>`.
        languages: ["ts", "js", "json", "bash", "html"],
    },
    themeConfig: {
        logo: "/icon.svg",
        search: { provider: "local" },
        nav: [
            { text: "Guide", link: "/guide/installation" },
            { text: "Reference", link: "/reference/" },
            {
                text: `v${SDK_VERSION}`,
                items: [{ text: "Releases", link: "https://github.com/lelantos-org/sdk/releases" }],
            },
        ],
        socialLinks: [{ icon: "github", link: "https://github.com/lelantos-org/sdk" }],
        editLink: {
            pattern: "https://github.com/lelantos-org/docs/edit/main/src/:path",
            text: "Edit this page on GitHub",
        },
        footer: { message: footerMessage },
        outline: [2, 3],
        sidebar: {
            "/guide/": guideSidebar,
            // Generated by TypeDoc into src/reference/ at build time;
            // regenerating is what keeps this in step with the exports map.
            "/reference/": [{ text: "Modules", items: typedocSidebar }],
        },
    },
});
