import { transformerTwoslash } from "@shikijs/vitepress-twoslash";
import { defineConfig } from "vitepress";
import typedocSidebar from "../reference/typedoc-sidebar.json" with { type: "json" };
import { SDK_VERSION } from "./config/build-info.ts";
import { footerMessage } from "./config/footer.ts";
import { guideSidebar } from "./config/sidebar.ts";
import { SITE_DESCRIPTION, SITE_TITLE, SITE_URL } from "./config/site.ts";
import { twoslashCompilerOptions } from "./config/twoslash.ts";

export default defineConfig({
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    lang: "en-US",
    cleanUrls: true,
    // A dead link is a docs bug; fail the build rather than ship one. The one
    // exemption is viem's own JSDoc, which reaches the reference through
    // ViemChainAdapter's inherited method docs and contains site-relative links
    // (/docs/glossary/terms#filter) that only resolve on viem.sh. Scoped to that
    // prefix so every other link stays checked.
    ignoreDeadLinks: [/^\/docs\/glossary\//],
    // Dark is the default across the wallet and the explorer; the docs follow.
    // Still toggleable — this sets which way an unstated preference falls.
    appearance: "dark",
    head: [
        ["link", { rel: "icon", href: "/icon.svg", type: "image/svg+xml" }],
        ["meta", { name: "theme-color", content: "#14110E" }],
        // The three faces the first screen is set in, fetched alongside the
        // HTML rather than after the CSS that names them has been parsed.
        // Newsreader sets the headings, which are the largest thing painted;
        // without the preload it swaps in late and reflows every section head.
        // `crossorigin` is required for fonts even on the same origin, or the
        // preloaded copy is not reused. Martian Mono is left out: it is 10KB
        // and only sets the wordmark.
        ...(["public-sans", "newsreader", "atkinson-hyperlegible-mono"].map((f) => [
            "link",
            {
                rel: "preload",
                href: `/fonts/${f}.woff2`,
                as: "font",
                type: "font/woff2",
                crossorigin: "",
            },
        ]) as [string, Record<string, string>][]),
        ["meta", { property: "og:type", content: "website" }],
        ["meta", { property: "og:title", content: SITE_TITLE }],
        ["meta", { property: "og:url", content: SITE_URL }],
    ],
    markdown: {
        // Warm-neutral, to sit on the warm ground. VitePress's default pair is
        // GitHub's, whose blue-violet keywords are the one cool thing left on
        // the page once the palette is the wallet's — and the accent is an
        // ember, so a violet keyword next to it reads as a second brand.
        // The block's own ground still comes from --vp-code-block-bg.
        theme: { light: "vitesse-light", dark: "vitesse-dark" },
        codeTransformers: [
            transformerTwoslash({
                // Never silently downgrade to plain highlighting: a snippet
                // that stops compiling must break the build, not the docs.
                throws: true,
                twoslashOptions: { compilerOptions: twoslashCompilerOptions },
            }),
        ],
        // Twoslash renders types into the DOM; Vue would try to parse the
        // braces in generic signatures like `Result<{ a: string }>`.
        languages: ["ts", "js", "json", "bash", "html"],
    },
    themeConfig: {
        logo: "/icon.svg",
        search: { provider: "local" },
        nav: [
            { text: "Guide", link: "/guide/installation" },
            { text: "Reference", link: "/reference/" },
            {
                text: `v${SDK_VERSION}`,
                items: [
                    { text: "Migrating from 0.38", link: "/guide/migration-0.38-to-0.39" },
                    { text: "Releases", link: "https://github.com/lelantos-org/sdk/releases" },
                ],
            },
        ],
        socialLinks: [{ icon: "github", link: "https://github.com/lelantos-org/sdk" }],
        editLink: {
            pattern: "https://github.com/lelantos-org/docs/edit/main/src/:path",
            text: "Edit this page on GitHub",
        },
        footer: { message: footerMessage },
        outline: [2, 3],
        sidebar: {
            "/guide/": guideSidebar,
            // Generated by TypeDoc into src/reference/ at build time;
            // regenerating is what keeps this in step with the exports map.
            "/reference/": [{ text: "Modules", items: typedocSidebar }],
        },
    },
});
